# The most straightforward way to add Postgres to our project is to do it with docker

version: "3"
services:
  postgres:
    container_name: nestjs-postgres
    image: postgres:latest
    ports:
      - "55000:5432"
    env_file:
      - docker.env
 
  pgadmin:
    container_name: nestjs-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    env_file:
      - docker.env
